# Generated by Django 3.2.16 on 2023-05-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='last_name',
            field=models.CharField(max_length=25),
        ),
    ]
