# Generated by Django 3.2.16 on 2023-05-22 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personal_Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(max_length=20, verbose_name='Nombre_Banco')),
                ('tipo_cuenta', models.CharField(max_length=40, verbose_name='Tipo_Cuenta')),
                ('numero_cuenta', models.CharField(max_length=20, verbose_name='Numero_Cuenta')),
            ],
        ),
    ]
