# Generated by Django 3.2.16 on 2023-05-18 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='apellido',
            field=models.CharField(max_length=40, verbose_name='apellidos_per'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='dv',
            field=models.CharField(max_length=1, verbose_name='digito_verificador'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='nombre',
            field=models.CharField(max_length=20, verbose_name='nombres_per'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='rut',
            field=models.CharField(max_length=9, verbose_name='rut'),
        ),
    ]
