# Generated by Django 3.2.16 on 2023-05-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_auto_20230518_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='apellido',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='personal',
            name='dv',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='personal',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='personal',
            name='rut',
            field=models.CharField(max_length=9),
        ),
    ]
