# Generated by Django 3.2.16 on 2023-05-30 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_auto_20230526_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='id',
        ),
        migrations.AddField(
            model_name='personal',
            name='personalId',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
